### ISSUE TITLE
Showname box in TextEvent requires enter press to save, Text box doesn't

### ISSUE THREAD

**Issue by Crystalwarrior** [AnidemDex/Godot-DialogPlugin#30]
Showname box for TextEvent should update itself any time a character is input or deleted, rather than any time Enter is pressed, because the RichText ui element is the former. Important for consistency

**Comment by AnidemDex** [comment]
[Looking at the code](https://github.com/AnidemDex/Godot-DialogPlugin/blob/main/addons/dialog_plugin/Nodes/editor_event_node/event_property_nodes/string_property/singleline/line_edit.gd#L16), it seems already fixed in the property node. It can not be updated every time you enter a charecter but it's updated every time it lost the focus.

Maybe was something related to #32 ?

**Comment by Crystalwarrior** [comment]
This still occurs

**Comment by AnidemDex** [comment]
Related to [`Nodes/misc/character_selector/character_selector.gd`](https://github.com/AnidemDex/Godot-DialogPlugin/blob/main/addons/dialog_plugin/Nodes/misc/character_selector/character_selector.gd)
